name: BungeePortals2
version: @version@
main: com.gmail.necnionch.myplugin.bungeeportals2.bukkit.BungeePortals2
#api-version: 1.13
depend: [WorldEdit]
authors: [Necnion8]

commands:
  bungeeportals:
    aliases: ["bportals"]
    permission: "bungeeportals2.command.bungeeportals"
    usage: "§c/BPortals <create/remove/info/list>"

